contracts/op-finality-gadget/schema/op-finality-gadget.json, contracts/op-finality-gadget/schema/raw/instantiate.json, contracts/op-finality-gadget/schema/raw/response_to_config.json, contracts/op-finality-gadget/src/contract.rs, contracts/op-finality-gadget/src/msg.rs, contracts/op-finality-gadget/src/state/config.rs, contracts/op-finality-gadget/tests/integration.rs
after https://github.com/babylonlabs-io/finality-provider/pull/42, we no longer need to read activated height from the cw contract.
instead, we properly find the time when the first delegation became active (see https://github.com/babylonchain/finality-provider/issues/432)
so this cleans up the unused field
```
cargo optimize
cargo precommit
cargo integration
cargo test
```
=> [OP] chore: remove unused activated_height

contracts/btc-finality/tests/integration.rs
=> Ignore now unsupported integration test

contracts/op-finality-gadget/src/contract.rs, contracts/op-finality-gadget/src/exec/finality.rs, contracts/op-finality-gadget/src/msg.rs, packages/bindings/src/msg.rs
This is a follow-on PR from https://github.com/babylonlabs-io/babylon-contract/pull/92 (implement slashing for op stack consumer chains)
It updates the `EquivocationEvidence` msg to match the latest Babylon update
```bash
cargo build
cargo optimize
cargo test
cargo integration
```
=> feat: op consumer chain slashing (2/2)

Cargo.lock, packages/test-utils/Cargo.toml, packages/test-utils/src/lib.rs
Generalise `test-utils` `testdata/` folder finding, so that `test-utils` can also be used as a non-local dependency (i.e. from the new https://github.com/babylonlabs-io/op-finality-gadget repo).
**TODO**:
=> Generalise testdata folder location finding

.github/workflows/deploy.yml, .github/workflows/local-tests.yml, contracts/babylon/Cargo.toml, contracts/btc-light-client/Cargo.toml, scripts/check-schema-naming.sh, scripts/schema.sh, scripts/set_version.sh
Currently, you'll see the following warning when running `cargo build`:
```
warning: output filename collision.
The bin target `schema` in package `btc-light-client v0.14.0 (/Users/xuliucheng/src/github.com/babylonlabs-io/cosmos-bsn-contracts/contracts/btc-light-client)` has the same output filename as the bin target `schema` in package `babylon-contract v0.14.0 (/Users/xuliucheng/src/github.com/babylonlabs-io/cosmos-bsn-contracts/contracts/babylon)`.
Colliding filename is: /Users/xuliucheng/src/github.com/babylonlabs-io/cosmos-bsn-contracts/target/debug/schema
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output …
```
=> fix: avoid output filename collision warning

.github/workflows/benchmarking.yml, .github/workflows/deploy.yml, .github/workflows/local-tests.yml, .github/workflows/wasm-tests-full.yml
Add concurrency groups with `cancel-in-progress` to all workflows to prevent multiple runs of the same workflow on the same PR/branch, improving CI resource usage and reducing queue times.
=> ci: add concurrency controls to GitHub workflows

.github/workflows/local-tests.yml, contracts/btc-staking/src/validation/mod.rs
This PR fixes an oversight in the clippy check.
=> ci: run clippy with `--all features` in local tests

packages/btcstaking/src/error.rs, packages/btcstaking/src/tx_verify.rs
Depends on #192 
Aligns the `validate_slashing_tx` method with the Babylon Genesis one.
=> chore: validate_slashing_tx in sync with Genesis

contracts/btc-staking/src/error.rs, contracts/btc-staking/src/staking.rs, contracts/btc-staking/src/validation/full.rs, contracts/btc-staking/src/validation/mod.rs
This PR is a pure refactor of the btc-staking contract in preparation for #7. The error handling are simplified a lot and now it's super clear what's the difference between the full and lite version of the validation after moving the full validation to a separate module. While there’s still room for further cleanup and modularization, I’m capping the scope here and starting to focus on implementing the remaining full-validation features. Further refinements may follow once the feature set stabilizes.
=> refactor: simplify btc staking contract

.github/workflows/deploy.yml
The full validation of btc staking contract is compiled in the pipeline but not include in the release artifacts.
A bit more thinking: Since now we are clear that we'll directly deploy the full validation version, perhaps it makes sense to remove the `full-validation` feature and make it default.
=> chore: include the btc_staking-full-validation.wasm in the release

contracts/btc-staking/src/error.rs, contracts/btc-staking/src/staking.rs, contracts/btc-staking/src/state/config.rs, contracts/btc-staking/src/state/delegations.rs, contracts/btc-staking/src/state/staking.rs, contracts/btc-staking/src/validation/full.rs, contracts/btc-staking/src/validation/mod.rs, packages/btcstaking/src/types.rs
This PR refactors the full validation logic to improve readability and efficiency ahead of #7. Review by commit is recommended.
Notably, [a12edcb](https://github.com/babylonlabs-io/cosmos-bsn-contracts/commit/a12edcb1cc64396680a4907b58a60c532fbb2d7d) might need a second look — unsure if the original logic was intentional.
Most changes are straightforward, but let me know if anything looks off.
=> refactor:  simplify the full validation module

contracts/babylon/src/contract.rs, contracts/babylon/src/error.rs, contracts/babylon/src/msg/contract.rs, contracts/babylon/src/multitest/suite.rs, contracts/babylon/tests/integration.rs, contracts/btc-finality/src/multitest/suite.rs
@SebastianElvis was right that `btc_light_client_initial_header` is unnecessary as it's already contained in the `btc_light_client_msg`. See https://github.com/babylonlabs-io/cosmos-bsn-contracts/pull/176#discussion_r2215338173 for more info.
=> chore: remove `btc_light_client_initial_header`

Cargo.lock, contracts/babylon/src/contract.rs, contracts/babylon/src/multitest.rs, contracts/babylon/src/multitest/suite.rs, contracts/babylon/tests/integration.rs, contracts/btc-finality/src/multitest/suite.rs, contracts/btc-light-client/benches/main.rs, contracts/btc-light-client/schema/btc-light-client.json, contracts/btc-light-client/schema/raw/instantiate.json, contracts/btc-light-client/src/bitcoin.rs, contracts/btc-light-client/src/contract.rs, contracts/btc-light-client/src/error.rs, contracts/btc-light-client/src/msg/btc_header.rs, contracts/btc-light-client/src/msg/contract.rs, contracts/btc-light-client/src/tests.rs, contracts/btc-light-client/tests/integration.rs, e2e/types/types.go, packages/proto/Cargo.toml, packages/proto/src/impl/babylon.btclightclient.v1.impl.rs, packages/proto/src/impls.rs, packages/proto/src/impls/babylon_btclightclient_v1.rs, packages/proto/src/impls/babylon_checkpointing_v1.rs, packages/proto/src/lib.rs, packages/test-utils/src/lib.rs
This PR includes a series of refactorings and improvements to the btc-light-client contract, focusing on code clarity, error handling, and adherence to Rust best practices.  Reviewing commit by commit and looking at the commit message should make the most sense.
Key Changes:
* **Naming and API Consistency:**
* Renamed `initial_header` to `base_header` for consistency. This is a breaking change :( @gitferry 
* Introduced a `block_header()` method for `BtcHeaderInfo`.
* **Simplified Header Processing:**
* The logic for processing BTC headers has been made more concise by extracting a `convert_to_btc_header_info` function and using `split_first` to handle the base header.
* The `init_btc_headers` function now accepts `first_work` by value since it's `Copy`, simplifying its signature.
* …
=> refactor(btc-light-client): Improve header processing and code quality

contracts/btc-light-client/src/bitcoin.rs, contracts/btc-light-client/src/msg/contract.rs
This fixes the misalignment in the difficulty block adjustment check. Can't recall why `height >= difficulty_adjustment_interval` was added previously, anyway, now it aligns with the Go implementation, with the reference attached in the comment. Not 100% if it's conceptually right that the block 0 is also a retarget block, but it's aligned at least :(
=> fix(btc-light-client): rename `is_difficulty_boundary()` to `is_retarget_block()` and fix the misalignment

contracts/btc-light-client/src/bitcoin.rs
This commit modifies the `total_work` function to support work values smaller than 32 bytes.
The `total_work` function now left-pads the input `work` byte slice with zeros to ensure it is 32 bytes long before converting it to a `Work` type.
=> feat(btc-light-client): pad work to 32 bytes

CHANGELOG.md, contracts/babylon/src/contract.rs, contracts/babylon/src/ibc.rs, contracts/babylon/src/multitest.rs, contracts/babylon/src/state/config.rs, contracts/babylon/src/state/consumer_header_chain.rs, contracts/babylon/src/state/mod.rs, contracts/babylon/src/utils/btc_light_client_executor.rs, contracts/babylon/src/utils/btc_light_client_querier.rs, contracts/btc-finality/src/multitest.rs, contracts/btc-light-client/src/contract.rs, e2e/types/test_client.go
This PR fixes various issues uncovered during debugging Babylon SDK e2e. These include
- Removing the concept of base BTC header completely in all contracts, not just BTC light client contract
- Using correct signing context for BSN FP slashing IBC packet
- Omitting unpacking certain fields in BTC timestamps
Prerequisite of https://github.com/babylonlabs-io/babylon-sdk/pull/182
=> fix: fix Babylon SDK e2e

CHANGELOG.md, contracts/btc-finality/src/contract.rs, contracts/btc-finality/src/finality.rs, contracts/btc-finality/src/msg.rs, contracts/btc-finality/src/multitest.rs, contracts/btc-finality/src/multitest/suite.rs, contracts/btc-finality/src/queries.rs, contracts/btc-finality/src/state/finality.rs, contracts/btc-light-client/src/msg/btc_header.rs, contracts/btc-staking/src/contract.rs, contracts/btc-staking/src/error.rs, contracts/btc-staking/src/msg.rs, contracts/btc-staking/src/queries.rs, contracts/btc-staking/src/staking.rs, contracts/btc-staking/src/state/fp_index.rs, contracts/btc-staking/src/state/staking.rs, packages/apis/src/btc_staking_api.rs
Resolves #156 
This PR fixes the voting power table bugs. This includes
=> finality: refactor voting power table in BTC finality contract, and fix finality signature handling/tallying

CHANGELOG.md, contracts/btc-finality/src/contract.rs, contracts/btc-finality/src/finality.rs, contracts/btc-finality/src/multitest.rs
This PR is primarily a refactor, with one exception: we now return an error on duplicated finality votes, as discussed in #263.
Main points:
- Eliminated several unnecessary allocations for efficiency.
- Renamed types to `MsgCommitPubRand` and `MsgAddFinalitySig` for clarity and consistency. (`MsgCommitPubRandList` felt a bit awkward, but happy to reconsider if there's a strong preference.)
Part of #263
=> finality: handle finality signature misalignment (part-2)

CHANGELOG.md, contracts/btc-finality/src/contract.rs, contracts/btc-finality/src/finality.rs, contracts/btc-finality/src/msg.rs, contracts/btc-finality/src/queries.rs, contracts/btc-finality/src/state/finality.rs
I'm not confident that the `signing_info()` query semantically aligns with the existing ones. Please take a closer look.
Close #269
=> finality: add missing finality queries

CHANGELOG.md, contracts/babylon/src/contract.rs, contracts/babylon/src/multitest/suite.rs, contracts/btc-finality/Cargo.toml, contracts/btc-finality/src/contract.rs, contracts/btc-finality/src/msg.rs, contracts/btc-staking/src/msg.rs, e2e/e2e_test.go, e2e/types/test_client.go, e2e/types/types.go, packages/apis/src/btc_staking_api.rs, packages/apis/src/finality_api.rs
Part of https://github.com/babylonlabs-io/pm/issues/461
This PR provides a minor refactoring of the instantiation messages for contracts. In particular, it 
- sets the consumer name/description outside of the if statements
- gives option to leave empty instantiation messages for BTC {light client, staking, finality} contracts
- if these instantiation messages are left empty, the handler will use values inside Babylon contract's instantiation message (which is recommended)
This PR also adapts e2e test to test this
=> chore: have default values for instantiation messages

CHANGELOG.md, contracts/btc-finality/Cargo.toml, contracts/btc-finality/src/finality.rs, contracts/btc-finality/src/msg.rs, contracts/btc-finality/src/multitest.rs, contracts/btc-finality/src/multitest/suite.rs, contracts/btc-finality/src/tests.rs, packages/eots/Cargo.toml, packages/eots/src/eots.rs, packages/eots/src/lib.rs, packages/merkle/src/hash.rs, packages/merkle/src/lib.rs, packages/merkle/src/tree.rs
This PR re-enables the EOTS signature check in tests, no logical changes in the production. It also adds back the code deleted in #258 for generating the commitment for the pub randomness list.
Resolves https://github.com/babylonlabs-io/cosmos-bsn-contracts/pull/304#discussion_r2258731544
=> chore: impl `gen_random_msg_commit_pub_rand()` properly and re-enable EOTS sig check in tests

CHANGELOG.md, contracts/btc-staking/schema/btc-staking.json, contracts/btc-staking/schema/raw/response_to_delegations.json, contracts/btc-staking/src/state/staking.rs
It is a legacy field which should be removed
=> chore: remove `slashed` from BtcDelegation

CHANGELOG.md, contracts/btc-finality/src/error.rs, contracts/btc-finality/src/finality.rs, contracts/btc-finality/src/state/finality.rs
In line with https://github.com/babylonlabs-io/babylon/blob/2f8df764e05edee36e896e957aa670b196da4d92/x/finality/keeper/msg_server.go#L114-L121
=> finality: return jailed FP error explicitly when handling finality signature

CHANGELOG.md, contracts/btc-light-client/Cargo.toml, contracts/btc-staking/Cargo.toml
full-validation contracts will still be generated using optimizer without the change in the PR
=> fix: avoid generating full-validation contracts

CHANGELOG.md, contracts/btc-finality/src/tallying.rs
This PR fixes the default size for `MAX_FINALIZED_REWARDED_BLOCKS_PER_END_BLOCK`. The previous default of `1_000` was too large for the default block gas limit and caused runtime errors when sending the `EndBlock` message to the BTC finality contract. With `1_000`, we observed panics such as:
```
10:16PM ERR Failed to send EndBlock message to BTC finality contract error="contract call to bbnc1ghd753shjuwexxywmgs4xz7x2q732vcnkm6h2pyv9s6ah3hylvrqv7u2f2 panicked: {Wasm engine function execution}, gas_used: 5000000" module=x/babylon
```
To prevent this, we picked a more conservative default range that fits safely within the block gas limit, ensuring EndBlock execution will not exceed gas and panic under normal conditions.
=> bugfix: out of gas on big batch
